name: Read Secrets
on:
  workflow_dispatch:

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  read_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Reading Secrets
        run: | 
          echo "Secrete Value: ${{ secrets.TEST_KEY }}"
          ${{ secrets.TEST_KEY }}
