name: Read Secrets
on:
  workflow_dispatch:

env:
  actions_steps_debug: true

jobs:
  read_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Reading Secrets
        run: | 
          echo "Secrete Value: ${{ secrets.TEST_KEY }}"
